KNOWLEDGE_BASE = [
    {
        "aliases": ["gato negro malbec", "gato negro malbec 2019"],
        "producer": "Gato Negro",
        "wine_name": "Malbec",
        "vintage": "2019",
        "grape": "Malbec",
        "country": "Chile",
        "region": "Central Valley",
        "subregion": "",
        "denomination": "",
        "classification": "",
        "wine_type": "Tinto",
        "alcohol": "13%",
        "aromas": "frutas vermelhas maduras, ameixa, notas frutadas",
        "palate": "macio, frutado, taninos suaves",
        "acidity": "média",
        "body": "médio",
        "soil": "",
        "climate": "mediterrâneo",
        "terroir": "",
        "aging": "",
        "pairing": "massas, carnes leves, pizzas",
        "notes": "Entrada de conhecimento-base"
    },
    {
        "aliases": ["catena malbec"],
        "producer": "Catena",
        "wine_name": "Malbec",
        "vintage": "",
        "grape": "Malbec",
        "country": "Argentina",
        "region": "Mendoza",
        "subregion": "",
        "denomination": "",
        "classification": "",
        "wine_type": "Tinto",
        "alcohol": "",
        "aromas": "violeta, ameixa, frutas negras",
        "palate": "frutado, estruturado",
        "acidity": "média",
        "body": "médio a encorpado",
        "soil": "aluvial",
        "climate": "continental seco",
        "terroir": "altitude andina",
        "aging": "",
        "pairing": "",
        "notes": "Entrada de conhecimento-base"
    },
    {
        "aliases": ["barolo docg 2018", "barolo 2018"],
        "producer": "",
        "wine_name": "Barolo",
        "vintage": "2018",
        "grape": "Nebbiolo",
        "country": "Itália",
        "region": "Piemonte",
        "subregion": "Barolo",
        "denomination": "Barolo DOCG",
        "classification": "DOCG",
        "wine_type": "Tinto",
        "alcohol": "",
        "aromas": "rosa, cereja, alcatrão",
        "palate": "estruturado, tânico, longo",
        "acidity": "alta",
        "body": "encorpado",
        "soil": "calcário, marga",
        "climate": "continental",
        "terroir": "Langhe",
        "aging": "maturação prolongada obrigatória",
        "pairing": "",
        "notes": "Entrada de conhecimento-base"
    },
    {
        "aliases": ["chablis premier cru", "chablis"],
        "producer": "",
        "wine_name": "Chablis Premier Cru",
        "vintage": "",
        "grape": "Chardonnay",
        "country": "França",
        "region": "Bourgogne",
        "subregion": "Chablis",
        "denomination": "Chablis Premier Cru",
        "classification": "AOC",
        "wine_type": "Branco",
        "alcohol": "",
        "aromas": "cítricos, maçã verde, mineral",
        "palate": "seco, tenso, mineral",
        "acidity": "alta",
        "body": "médio",
        "soil": "Kimmeridgian",
        "climate": "frio continental",
        "terroir": "encostas calcárias de Chablis",
        "aging": "",
        "pairing": "frutos do mar",
        "notes": "Entrada de conhecimento-base"
    }
]
